base/urls.py
from django.urls import path
from base import views


urlpatterns = [
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("sing-up/", views.register, name="register"),
    path("", views.home, name="home"),
    path("room/<str:pk>/", views.room, name="room"),
    path("topics/", views.topics, name="topics"),
    path("activities/", views.activities, name="activities"),
    path("profile/<str:pk>", views.userProfile, name="user-profile"),
    path("user-settings/", views.userSettings, name="user-settings"),
    path("create-room/", views.createRoom, name="create-room"),
    path("update-room/<str:pk>/", views.updateRoom, name="update-room"),
    path("delete-room/<str:pk>/", views.deleteRoom, name="delete-room"),
    path("delete-message/<str:pk>/", views.deleteMessage, name="delete-message"),
]

server_files/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    email = models.EmailField(max_length=256, unique=True, null=True)
    username = models.CharField(max_length=256, unique=True)
    name = models.CharField(max_length=256, null=True)
    about = models.TextField(max_length=512, blank=True)

    avatar = models.ImageField(null=True, default="avatar.svg")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self) -> str:
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    room_name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True, max_length=256)
    participants = models.ManyToManyField(User, related_name="participants", blank=True)
    updated = models.DateTimeField(auto_now=True)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated", "-create_time"]

    def __str__(self) -> str:
        return self.room_name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from base.models import Room, User


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["avatar", "email", "username", "name", "about"]
        exclude =[""]


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = [
            "topic",
            "room_name",
            "description",
        ]
        # exclude = ['host', 'participants']


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "name", "username", "password1", "password2"]

base/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse
from base.models import Room, Topic, Message, User
from base.forms import RoomForm, UserForm, MyUserCreationForm

# Create your views here.


# Login User
def loginPage(request):
    page = "login"

    # if user is logged in, shouldn't able to login again
    if request.user.is_authenticated:
        return redirect("home")

    if request.method == "POST":
        email = request.POST.get("email").lower()
        password = request.POST.get("password")

        # try to find user in database
        try:
            user = User.objects.get(email=email)
        # if user is not registered
        except:
            messages.error(request, "Invalid login credentials")

        user = authenticate(request=request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect("home")

    context = {"page": page}
    return render(request, "base/login_register.html", context)


# Logout user
def logoutUser(request):
    logout(request)
    return redirect("home")


# Register user
def register(request):
    # create form object for user registration
    form = MyUserCreationForm()

    # register new user
    if request.method == "POST":
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.email = user.email.lower()
            user.username = user.username.lower()
            user = form.save()
            login(request, user)
            return redirect("home")
        else:
            messages.error(request, "An error occurred during registration")

    context = {"form": form}
    return render(request, "base/login_register.html", context)


# main page
def home(request):
    # looks if "q" exists, it search in all sections to find matches
    q = request.GET.get("q") if request.GET.get("q") != None else ""

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q)
        | Q(room_name__icontains=q)
        | Q(description__icontains=q)
    )

    topics = Topic.objects.all()[0:5]
    room_count = rooms.count()

    recent_activities = Message.objects.filter(
        Q(room__topic__name__icontains=q)
    ).order_by("-create_time")[0:4]

    context = {
        "rooms": rooms,
        "topics": topics,
        "room_count": room_count,
        "recent_activities": recent_activities,
    }

    return render(request, "base/home.html", context)


# room page
def room(request, pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all().order_by("create_time")
    participants = room.participants.all()

    # create new comment and add it to database
    if request.method == "POST":
        if request.user.is_authenticated:
            Message.objects.create(
                user=request.user,
                room=room,
                body=request.POST.get("body"),
            )
            if room.host != request.user:
                room.participants.add(request.user)
            return redirect("room", pk=room.id)

    context = {
        "room": room,
        "room_messages": room_messages,
        "participants": participants,
    }

    return render(request, "base/room.html", context)


# topic page
def topics(request):
    q = request.GET.get("q") if request.GET.get("q") != None else ""
    topics = Topic.objects.filter(name__icontains=q)

    return render(request, "base/topics.html", {"topics": topics})


def activities(request):
    activities = Message.objects.filter().order_by("-create_time")

    return render(request, "base/activities.html", {"activities": activities})


@login_required(login_url="/login")
def userProfile(request, pk):
    user = User.objects.get(username=pk)
    rooms = user.room_set.all()
    recent_activities = user.message_set.all().order_by("-create_time")
    topics = Topic.objects.all()

    context = {
        "user": user,
        "rooms": rooms,
        "recent_activities": recent_activities,
        "topics": topics,
    }
    return render(request, "base/user_profile.html", context)


# user settings page
@login_required(login_url="login")
def userSettings(request):
    user = request.user

    # create object for user settings
    form = UserForm(instance=user)

    # update user credentials
    if request.method == "POST":
        # request.FILES.
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect("user-profile", pk=user.username)

    # user validation and render setting page
    try:
        query = User.objects.filter(username=user.username).first()
        if query == user:
            context = {"form": form}
            return render(request, "base/user_settings.html", context)
        else:
            return HttpResponse("You are not allowed to edit this room")
    except:
        messages.error(request, "Error creating user settings")


@login_required(login_url="/login")
def createRoom(request):
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == "POST":
        topic_name = request.POST.get("topic")
        topic, created = Topic.objects.get_or_create(name=topic_name)
        print("\n\n\n\n\n\n", created, "\n\n\n\n\n\n")
        if created:
            Room.objects.create(
                host=request.user,
                topic=topic,
                room_name=request.POST.get("room_name"),
                description=request.POST.get("description"),
            )
        else:
            Room.objects.create(
                host=request.user,
                topic=topic,
                room_name=request.POST.get("room_name"),
                description=request.POST.get("description"),
            )

        return redirect("home")

    context = {"form": form, "topics": topics}

    return render(request, "base/room_form.html", context)


@login_required(login_url="/login")
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    room_update = True
    if request.user != room.host:
        return HttpResponse("You are not allowed to edit this room")

    else:
        form = RoomForm(instance=room)

        if request.method == "POST":
            room.description = request.POST.get("description")

            room.save()

            return redirect("home")

    context = {"form": form, "room": room, "room_update": room_update}
    return render(request, "base/room_form.html", context)


@login_required(login_url="/login")
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk)

    if request.user != room.host:
        return HttpResponse("You are not allowed to delete this room")

    if request.method == "POST":
        room.delete()
        return redirect("home")

    return render(request, "base/delete.html", {"obj": room})


@login_required(login_url="/login")
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse("You are not allowed to delete this Message")

    if request.method == "POST":
        message.delete()
        return redirect("home")

    return render(request, "base/delete.html", {"obj": message})

base/templates/base/activities.html
{% extends 'main.html' %}

{% block content %}
<main class="layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
              </path>
            </svg>
          </a>
          <h3>Recent Activities</h3>
        </div>
      </div>

      <div class="activities-page layout__body">

        {% for activity in activities %}
        <div class="activities__box">
          <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' activity.user.username %}" class="roomListRoom__author">
              <div class="avatar avatar--small">
                <img src="{{activity.user.avatar.url}}" />
              </div>
              <p>
                @{{activity.user.username}}
                <span>{{activity.created|timesince}} ago</span>
              </p>
            </a>

            {% if request.user == activity.user %}
            <div class="roomListRoom__actions">
              <a href="{% url 'delete-message' activity.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                  </path>
                </svg>
              </a>
            </div>
            {% endif %}

          </div>
          <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'room' activity.room.id %}">{{activity.room}}</a>”</p>
            <div class="activities__boxRoomContent">
              {{activity.body}}
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>
</main>
{% endblock content %}

base/templates/base/create-room.html
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Create Study Room</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="#">
          <div class="form__group">
            <label for="room_name">Room Name</label>
            <input id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" />
          </div>

          <div class="form__group">
            <label for="room_topic">Topic</label>
            <input required type="text" name="topic" id="room_topic" list="topic-list" />
            <datalist id="topic-list">
              <select id="room_topic">
                <option value="">Select your topic</option>
                <option value="Python">Python</option>
                <option value="Django">Django</option>
              </select>
            </datalist>

          </div>


          <div class="form__group">
            <label for="room_about">About</label>
            <textarea name="room_about" id="room_about" placeholder="Write about your study group..."></textarea>
          </div>
          <div class="form__action">
            <a class="btn btn--dark" href="index.html">Cancel</a>
            <button class="btn btn--main" type="submit">Create Room</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}

{% if request.user.is_authenticated %}

<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete {{obj}}?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Delete" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>

{% endif %}

{% endblock content %}

base/templates/base/home.html
{% extends 'main.html' %} {% block content %}

<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'base/components/topics_comp.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form method="GET" action="" class="header__search">
          <label>
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input type="text" name="q" placeholder="Search for rooms..." />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'topics' %}"
            >Browse Topics</a
          >
          <a class="btn btn--main btn--pill" href="{% url 'activities' %}"
            >Recent Activities</a
          >
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Rooms</h2>
          <p>{{rooms.count}} rooms available</p>
        </div>

        {% if request.user.is_authenticated %}
        <a class="btn btn--main" href="{% url 'create-room' %}">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
            ></path>
          </svg>
          Create Room
        </a>
        {% endif %}
      </div>
      {% include 'base/components/feeds_comp.html' %}
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/components/activity_comp.html'%}
    <!-- Activities End -->
  </div>
</main>

{% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %} {% block content %}

<main class="auth layout">
  <div class="container">
    <div class="layout__box">
      {% if page == "login" %}

      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST">
          {% csrf_token %}
          <div class="form__group form__group">
            <label for="room_name">Email</label>
            <input
              id="email"
              name="email"
              type="text"
              placeholder="e.g. user@example.com"
            />
          </div>
          <div class="form__group">
            <label for="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
            />
          </div>

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Login
          </button>
        </form>

        <div class="auth__action">
          <p>Haven't signed up yet?</p>
          <a href="{% url 'register'%}" class="btn btn--link">Sign Up</a>
        </div>
      </div>

      {% else %}

      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Sign up</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST">
          {% csrf_token %} {% for field in form %}
          <div class="form__group form__group">
            <label for="fullname">{{field.label}}</label>
            {{field}}
          </div>
          {% endfor %}
          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Sign Up
          </button>
        </form>

        <div class="auth__action">
          <p>Already have an account?</p>
          <a href="{% url 'login'%}" class="btn btn--link">Log In</a>
        </div>
      </div>

      {% endif %}
    </div>
  </div>
</main>

{% endblock content %}

base/templates/base/recent_activities.html
{% extends 'main.html' %}

{% block content %}

<main class="layout">
    <div class="container">
    <div class="layout__box">
        <div class="layout__boxHeader">
        <div class="layout__boxTitle">
            <a href="index.html">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
            </svg>
            </a>
            <h3>Recent Activities</h3>
        </div>
        </div>

        <div class="activities-page layout__body">
        <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
            <a href="profile.html" class="roomListRoom__author">
                <div class="avatar avatar--small">
                <img src="https://randomuser.me/api/portraits/women/11.jpg" />
                </div>
                <p>
                @sulamita_ivy
                <span>5 days ago</span>
                </p>
            </a>
            <div class="roomListRoom__actions">
                <a href="#">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                </svg>
                </a>
            </div>
            </div>
            <div class="activities__boxContent">
            <p>replied to post “<a href="room.html">100 Days of code challenge!</a>”</p>
            <div class="activities__boxRoomContent">
                I’ll have to try this sometime. Really like this idea. Wanna talk about it? I ‘m....
            </div>
            </div>
        </div>

        <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
            <a href="profile.html" class="roomListRoom__author">
                <div class="avatar avatar--small active">
                <img src="https://randomuser.me/api/portraits/men/13.jpg" />
                </div>
                <p>
                @mr_spshuvo
                <span>5 days ago</span>
                </p>
            </a>
            <div class="roomListRoom__actions">
                <a href="#">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                </svg>
                </a>
            </div>
            </div>
            <div class="activities__boxContent">
            <p>replied to post “<a href="room.html">100 Days of code challenge!</a>”</p>
            <div class="activities__boxRoomContent">
                I’ll have to try this sometime. Really like this idea. Wanna talk about it? I ‘m....
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}

base/templates/base/room_form.html
{% extends 'main.html' %}

{% block content %}

{% if request.user.is_authenticated %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Create Study Room</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="#" method="POST">
        {% csrf_token %}
          <div class="form__group">
            <label for="room_name">Room Name</label>
            {% comment %} {{form.room_name}} {% endcomment %}
            <input required type="text" value="{{room.room_name}}" maxlength="200" name="room_name" id="id_room_name" 
            {% if room_update == True %}disabled{% endif %}
            />
          </div>

          <div class="form__group">
            <label for="room_topic">Topic</label>
            <input required type="text" value="{{room.topic.name}}" name="topic" list="topic-list" 
            {% if room_update == True %}disabled{% endif %}
            />
            <datalist id="topic-list">
              <select id="room_topic">

                {% for topic in topics %}
                <option value="{{topic.name}}">{{topic.name}}</option>
                {% endfor %}

              </select>
            </datalist>

          </div>


          <div class="form__group">
            <label for="room_about">About</label>
            {{form.description}}
            {% comment %} <textarea name="room_about" id="room_about" placeholder="Write about your study group..."></textarea> {% endcomment %}
          </div>
          <div class="form__action">
            <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}">Cancel</a>
            <button class="btn btn--main" type="submit">
                {% if room_update == True %}
                Update Room
                {% else %}
                Create Room
                {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>


{% endif%}


{% endblock %}

base/templates/base/topics.html
{% extends 'main.html' %}

{% block content %}



<main class="create-room layout">
    <div class="container">
    <div class="layout__box">
        <div class="layout__boxHeader">
        <div class="layout__boxTitle">
            <a href="{{request.META.HTTP_REFERER}}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
            </svg>
            </a>
            <h3>Browse Topics</h3>
        </div>
        </div>

        <div class="topics-page layout__body">
        <form class="header__search" method="GET" action="{% url 'topics' %}">
            <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>search</title>
                <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                ></path>
            </svg>
            <input type="text" name="q" placeholder="Search for Topics" />
            </label>
        </form>

        <ul class="topics__list">
            <li>
            <a href="/" class="active">All <span>{{topics.count}}</span></a>
            </li>

            {% for topic in topics%}
            <li>
                <a href="{% url 'home' %}?q={{topic.name}}">{{topic.name}}
                    <span>{{topic.room_set.all.count}}</span>
                </a>
            </li>
            {% endfor %}
        </ul>
        </div>
    </div>
    </div>
</main>

{% endblock %}